FROM nvcr.io/nvidia/isaac-sim:5.0.0

# 기본 파일 설치
RUN apt-get update && \
    apt-get install -y \
    vim \
    nano \
    wget \
    curl \
    git \
    git-lfs \
    libeigen3-dev

# cuda toolkit 12.8 설치
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin && \
    mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600 && \
    wget https://developer.download.nvidia.com/compute/cuda/12.8.0/local_installers/cuda-repo-ubuntu2204-12-8-local_12.8.0-570.86.10-1_amd64.deb && \
    dpkg -i cuda-repo-ubuntu2204-12-8-local_12.8.0-570.86.10-1_amd64.deb && \
    cp /var/cuda-repo-ubuntu2204-12-8-local/cuda-*-keyring.gpg /usr/share/keyrings/ && \
    apt-get update && \
    apt-get -y install cuda-toolkit-12-8


# cuRobo 설치

# 환경변수 설정
ENV PATH=${PATH}:/usr/local/cuda-12.8/bin
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-12.8/lib64

# GPU architecture 지정 (사용하는 GPU에 맞게 조정, RTX 50 series)
ENV TORCH_CUDA_ARCH_LIST="12.0"

RUN echo 'export PATH=${PATH}:/usr/local/cuda-12.8/bin' >> /root/.bashrc && \
    echo 'export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-12.8/lib64' >> /root/.bashrc && \
    echo "alias omni_python='/isaac-sim/python.sh'" >> /root/.bashrc

RUN /isaac-sim/python.sh -m pip install tomli wheel ninja

WORKDIR /
RUN git clone https://github.com/NVlabs/curobo.git
WORKDIR /curobo

RUN /isaac-sim/python.sh -m pip install -e ".[isaacsim]" --no-build-isolation

# vision_inspection clone 및 파일 이동
WORKDIR /curobo
RUN git clone https://github.com/Sungjin-Park-dev/vision_inspection_sogang.git && \
    cp /curobo/vision_inspection_sogang/ur20_description/ur20.yml /curobo/src/curobo/content/configs/robot/ && \
    cp /curobo/vision_inspection_sogang/ur20_description/ur20.urdf /curobo/src/curobo/content/assets/robot/ur_description/ && \
    cp -r /curobo/vision_inspection_sogang/ur20_description/ur20 /curobo/src/curobo/content/assets/robot/ur_description/meshes/


RUN /isaac-sim/python.sh -m pip install open3d EAIK h5py